/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package update.dyno;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.document.UpdateItemOutcome;
import com.amazonaws.services.dynamodbv2.document.spec.UpdateItemSpec;
import com.amazonaws.services.dynamodbv2.document.utils.ValueMap;
import com.amazonaws.services.lambda.runtime.Context;


public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "Taskmaster";
    private Regions REGION = Regions.US_WEST_2;

    public String update(String id, Context context) {
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        DynamoDB dynamoDB = new DynamoDB(ddb);

        Table table = dynamoDB.getTable("Taskmaster");
        UpdateItemSpec updateItemSpec = new UpdateItemSpec().withPrimaryKey("id", id).withUpdateExpression("set iMG= :u").withValueMap(new ValueMap().withString(":u", "Everything happens all at once."));
        UpdateItemOutcome outcome = table.updateItem(updateItemSpec);
        return id;
    }
}